// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bootstrap

// Injectors from wire.go:

func InitializeAPIApp() (*APIApp, func(), error) {
	config := ProvideConfig()
	logger, cleanup, err := ProvideLogger(config)
	if err != nil {
		return nil, nil, err
	}
	client, cleanup2, err := ProvideRedis(config)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	healthHandler := ProvideHealthHandler(config, client)
	engine := ProvideGinEngine(config, logger, healthHandler)
	server := ProvideHTTPServer(config, engine)
	duration := ProvideShutdownTimeout(config)
	apiApp := ProvideAPIApp(server, logger, duration)
	return apiApp, func() {
		cleanup2()
		cleanup()
	}, nil
}
